# Recomendação de Parâmetros em Workflows Científicos

### 1 -  Lendos os dados

In [88]:
import pandas as pd
#lendo dados originais
data = pd.read_csv('data.csv')
data.head()

   num_aligns  length model1        prob1 model2        prob2   erro
0        10.0   237.0  WAG+G  1588.458801  WAG+G  1588.458801  False
1        10.0   237.0  WAG+G  1588.458801  WAG+G  1588.458801  False
2        10.0   237.0  WAG+G  1588.458801  WAG+G  1588.458801  False
3        10.0   237.0  WAG+G  1588.458801  WAG+G  1588.458801  False
4        10.0   237.0  WAG+G  1588.458801  WAG+G  1588.458801  False

In [89]:
#selecionando apenas os dados de execução de sucesso
data[data['erro'] == False]
data = data.drop('erro', 1)
#forço as colunas de prob serem strings para o one hot encoding levá-las em consideração
data['prob1'] = data['prob1'].astype(str)
data['prob2'] = data['prob2'].astype(str)
#convertendo features categoricas em binarias
data = pd.get_dummies(data)
data.head()

,num_aligns,length,model1_BLOSUM62,model1_BLOSUM62+F,model1_BLOSUM62+G,model1_BLOSUM62+G+F,model1_BLOSUM62+I,model1_BLOSUM62+I+F,model1_BLOSUM62+I+G+F,model1_CPREV+G+F,...,prob2_635.874188478,prob2_655.23910026,prob2_657.617722881,prob2_703.934317936,prob2_787.499472235,prob2_804.670440867,prob2_804.952769924,prob2_836.781299518,prob2_917.715801421,prob2_991.427723496
0,10.0,237.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10.0,237.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10.0,237.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10.0,237.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,10.0,237.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [90]:
#convertendo data em transposta
data = data.transpose()
data.head()

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
num_aligns,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
length,237.0,237.0,237.0,237.0,237.0,237.0,237.0,237.0,237.0,237.0,...,237.0,342.0,479.0,219.0,194.0,151.0,237.0,237.0,237.0,237.0
model1_BLOSUM62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
model1_BLOSUM62+F,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
model1_BLOSUM62+G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [91]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
#treinando o KNN
model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(data)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [107]:
print('Data shape: %s' % data.shape[0] )
#escolho uma feature aletória (row de data)
query_index = np.random.choice(data.shape[0])
print('Query Index: %i' % query_index )
feature_base = data.iloc[query_index, :].values.reshape(1, -1)
print('Feature Base: %s' % feature_base )

distances, indices = model_knn.kneighbors(feature_base, n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(data.index[query_index]) )
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, data.index[indices.flatten()[i]], distances.flatten()[i]))

Data shape: 405
Query Index: 59
Feature Base: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]]
Recommendations for prob1_1385.758743:

1: prob1_1385.758743, with distance of 0.0:
2: model1_BLOSUM62+G, with distance of 0.5917517095361369:
3: model2_BLOSUM62+G, with distance of 0.75:
4: num_aligns, with distance of 0.9501969551180866:
5: length, with distance of 0.9770587123879868: